title: "Learning Collaborative Report: August 2024"
date: now
date-format: long
title-block-banner: true
format: flexdashboard::flex_dashboard
execute:
    echo: false
project: 
    output-dir: Outputs
    execute-dir: file
